/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plasma2;

import Medusa_pkg.BarGaugePanel;
import eu.hansolo.medusa.Gauge;
import java.awt.BorderLayout;
import java.awt.Component;
import java.util.Random;

/**
 *
 * @author guillaume
 */
public class DashBoardPanel extends javax.swing.JPanel {
    
    java.awt.Color awtColor = getBackground() ;
    int r = 35;
    int g = 38;
    int b = 43;
    int a = 255;
    double opacity = a / 255.0 ;
    javafx.scene.paint.Color fxColor = javafx.scene.paint.Color.rgb(r, g, b, opacity);
      private final  BarGaugePanel barGauge = new BarGaugePanel(Gauge.SkinType.AMP, fxColor);
      private final  BarGaugePanel barGauge2 = new BarGaugePanel(Gauge.SkinType.GAUGE,fxColor);
      private final  BarGaugePanel barGauge3 = new BarGaugePanel(Gauge.SkinType.MODERN,fxColor);
      private final  BarGaugePanel barGauge4 = new BarGaugePanel(Gauge.SkinType.DIGITAL,fxColor);
      private final  BarGaugePanel barGauge5 = new BarGaugePanel(Gauge.SkinType.TILE_SPARK_LINE,fxColor);
      private final  BarGaugePanel barGauge6 = new BarGaugePanel(Gauge.SkinType.SPACE_X,fxColor);
      private final  BarGaugePanel barGauge7 = new BarGaugePanel(Gauge.SkinType.LEVEL,fxColor);
      private final  BarGaugePanel barGauge8 = new BarGaugePanel(Gauge.SkinType.LCD,fxColor);
      private final  BarGaugePanel barGauge9 = new BarGaugePanel(Gauge.SkinType.SLIM,fxColor);
      private final  BarGaugePanel barGauge10 = new BarGaugePanel(Gauge.SkinType.QUARTER,fxColor);
      private final  BarGaugePanel barGauge11 = new BarGaugePanel(Gauge.SkinType.SIMPLE,fxColor);
      private final  BarGaugePanel barGauge12 = new BarGaugePanel(Gauge.SkinType.BATTERY,fxColor);
      private final  BarGaugePanel barGauge13 = new BarGaugePanel(Gauge.SkinType.VERTICAL,fxColor);
      private final  BarGaugePanel barGauge14 = new BarGaugePanel(Gauge.SkinType.BAR,fxColor);
      private final  graphWebView  Graph1 = new graphWebView();
      private static final Random RND = new Random();
    /**
     * Creates new form DashBoardPanel
     */
    public DashBoardPanel() {
                
        initComponents();
        
        // set tous les Jpanel en borderLayout
        for (Component c : this.getComponents()) {
            if (c instanceof javax.swing.JPanel) {
               ((javax.swing.JPanel)c).setLayout(new BorderLayout());
            }
        }
        // ajout des composents "dashboard"
       
        jPanel_Graph.add(Graph1);
        jPanel_gauge1.add(barGauge9);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPAnel_TaskInProgress = new javax.swing.JPanel();
        jPanel_Graph = new javax.swing.JPanel();
        jPanel_GMF = new javax.swing.JPanel();
        jPanel_gauge1 = new javax.swing.JPanel();
        jPanel_gauge2 = new javax.swing.JPanel();
        jPanel_gauge3 = new javax.swing.JPanel();
        jPanel_gauge4 = new javax.swing.JPanel();
        jPanel_gauge5 = new javax.swing.JPanel();

        jCheckBox1.setText("jCheckBox1");

        setBackground(new java.awt.Color(35, 38, 43));
        setPreferredSize(new java.awt.Dimension(1212, 732));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPAnel_TaskInProgress.setBackground(new java.awt.Color(200, 200, 200));
        jPAnel_TaskInProgress.setPreferredSize(new java.awt.Dimension(1200, 150));

        javax.swing.GroupLayout jPAnel_TaskInProgressLayout = new javax.swing.GroupLayout(jPAnel_TaskInProgress);
        jPAnel_TaskInProgress.setLayout(jPAnel_TaskInProgressLayout);
        jPAnel_TaskInProgressLayout.setHorizontalGroup(
            jPAnel_TaskInProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPAnel_TaskInProgressLayout.setVerticalGroup(
            jPAnel_TaskInProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        jPanel_Graph.setBackground(new java.awt.Color(200, 200, 200));
        jPanel_Graph.setToolTipText("");
        jPanel_Graph.setPreferredSize(new java.awt.Dimension(700, 300));

        javax.swing.GroupLayout jPanel_GraphLayout = new javax.swing.GroupLayout(jPanel_Graph);
        jPanel_Graph.setLayout(jPanel_GraphLayout);
        jPanel_GraphLayout.setHorizontalGroup(
            jPanel_GraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_GraphLayout.setVerticalGroup(
            jPanel_GraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel_GMF.setBackground(new java.awt.Color(200, 200, 200));
        jPanel_GMF.setPreferredSize(new java.awt.Dimension(225, 225));

        javax.swing.GroupLayout jPanel_GMFLayout = new javax.swing.GroupLayout(jPanel_GMF);
        jPanel_GMF.setLayout(jPanel_GMFLayout);
        jPanel_GMFLayout.setHorizontalGroup(
            jPanel_GMFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_GMFLayout.setVerticalGroup(
            jPanel_GMFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        jPanel_gauge1.setBackground(new java.awt.Color(200, 200, 200));
        jPanel_gauge1.setPreferredSize(new java.awt.Dimension(225, 225));

        javax.swing.GroupLayout jPanel_gauge1Layout = new javax.swing.GroupLayout(jPanel_gauge1);
        jPanel_gauge1.setLayout(jPanel_gauge1Layout);
        jPanel_gauge1Layout.setHorizontalGroup(
            jPanel_gauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        jPanel_gauge1Layout.setVerticalGroup(
            jPanel_gauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        jPanel_gauge2.setBackground(new java.awt.Color(200, 200, 200));
        jPanel_gauge2.setPreferredSize(new java.awt.Dimension(225, 225));

        javax.swing.GroupLayout jPanel_gauge2Layout = new javax.swing.GroupLayout(jPanel_gauge2);
        jPanel_gauge2.setLayout(jPanel_gauge2Layout);
        jPanel_gauge2Layout.setHorizontalGroup(
            jPanel_gauge2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        jPanel_gauge2Layout.setVerticalGroup(
            jPanel_gauge2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        jPanel_gauge3.setBackground(new java.awt.Color(200, 200, 200));
        jPanel_gauge3.setPreferredSize(new java.awt.Dimension(225, 225));

        javax.swing.GroupLayout jPanel_gauge3Layout = new javax.swing.GroupLayout(jPanel_gauge3);
        jPanel_gauge3.setLayout(jPanel_gauge3Layout);
        jPanel_gauge3Layout.setHorizontalGroup(
            jPanel_gauge3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        jPanel_gauge3Layout.setVerticalGroup(
            jPanel_gauge3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel_gauge4.setBackground(new java.awt.Color(200, 200, 200));
        jPanel_gauge4.setPreferredSize(new java.awt.Dimension(225, 225));

        javax.swing.GroupLayout jPanel_gauge4Layout = new javax.swing.GroupLayout(jPanel_gauge4);
        jPanel_gauge4.setLayout(jPanel_gauge4Layout);
        jPanel_gauge4Layout.setHorizontalGroup(
            jPanel_gauge4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        jPanel_gauge4Layout.setVerticalGroup(
            jPanel_gauge4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel_gauge5.setBackground(new java.awt.Color(200, 200, 200));
        jPanel_gauge5.setPreferredSize(new java.awt.Dimension(225, 225));

        javax.swing.GroupLayout jPanel_gauge5Layout = new javax.swing.GroupLayout(jPanel_gauge5);
        jPanel_gauge5.setLayout(jPanel_gauge5Layout);
        jPanel_gauge5Layout.setHorizontalGroup(
            jPanel_gauge5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        jPanel_gauge5Layout.setVerticalGroup(
            jPanel_gauge5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPAnel_TaskInProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel_Graph, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_GMF, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_gauge1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_gauge2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_gauge3, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_gauge4, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_gauge5, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPAnel_TaskInProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_GMF, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(jPanel_Graph, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_gauge2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_gauge1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel_gauge3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_gauge4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_gauge5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        try {

    // exceptional block of code ...
        barGauge.SetValue(RND.nextDouble() * 100.0);
        barGauge2.SetValue(RND.nextDouble() * 100.0);
        barGauge3.SetValue(RND.nextDouble() * 100.0);
        barGauge4.SetValue(RND.nextDouble() * 100.0);
        barGauge5.SetValue(RND.nextDouble() * 100.0);
        barGauge6.SetValue(RND.nextDouble() * 100.0);
        barGauge7.SetValue(RND.nextDouble() * 100.0);
        barGauge8.SetValue(RND.nextDouble() * 100.0);
        barGauge9.SetValue(RND.nextDouble() * 100.0);
        barGauge10.SetValue(RND.nextDouble() * 100.0);
        barGauge11.SetValue(RND.nextDouble() * 100.0);
        barGauge12.SetValue(RND.nextDouble() * 100.0);
        barGauge13.SetValue(RND.nextDouble() * 100.0);
        barGauge14.SetValue(RND.nextDouble() * 100.0);
        //Graph1.SetValue(RND.nextDouble() * 100.0);
    // ...

        } catch (Exception e){

            // Deal with e as you please.
            //e may be any type of exception at all.

        }
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPAnel_TaskInProgress;
    private javax.swing.JPanel jPanel_GMF;
    private javax.swing.JPanel jPanel_Graph;
    private javax.swing.JPanel jPanel_gauge1;
    private javax.swing.JPanel jPanel_gauge2;
    private javax.swing.JPanel jPanel_gauge3;
    private javax.swing.JPanel jPanel_gauge4;
    private javax.swing.JPanel jPanel_gauge5;
    // End of variables declaration//GEN-END:variables
}